# Generated by Django 2.2.5 on 2020-12-04 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('supplier', models.CharField(max_length=50)),
                ('order_date', models.DateField(default=None)),
                ('order_no', models.IntegerField()),
                ('quantity', models.FloatField()),
                ('rem_quantity', models.FloatField(null=True)),
                ('rate', models.FloatField()),
                ('amount', models.FloatField(max_length=15)),
                ('state', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50, null=True)),
                ('bill_no', models.IntegerField(null=True)),
                ('bill_date', models.DateField(default=None, null=True)),
                ('validation', models.CharField(default='No', max_length=50, null=True)),
                ('chalan_no', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArrivalLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Checker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checker', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClosingStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('unit', models.CharField(max_length=50, null=True)),
                ('dailydate', models.DateField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('quantity', models.FloatField(default=0.0, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ColorRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('supplier', models.CharField(max_length=50)),
                ('order_date', models.DateField(default=None)),
                ('order_no', models.IntegerField()),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=50, null=True)),
                ('rate', models.FloatField()),
                ('amount', models.FloatField(max_length=15)),
                ('state', models.CharField(max_length=50)),
                ('recieving_date', models.DateField(default=None, null=True)),
                ('total_quantity', models.FloatField()),
                ('godown', models.CharField(default='-', max_length=50)),
                ('lease', models.CharField(default='-', max_length=50)),
                ('bill_no', models.IntegerField(null=True)),
                ('bill_date', models.DateField(default=None, null=True)),
                ('chalan_no', models.IntegerField(null=True)),
                ('recieving_date_string', models.CharField(default=None, max_length=20, null=True)),
                ('b_date', models.DateField(default=None, null=True)),
                ('a', models.CharField(default='-', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ColorSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_account', models.CharField(max_length=11)),
                ('account_name', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=11, null=True)),
                ('bank_name', models.CharField(max_length=50, null=True)),
                ('branch_code', models.CharField(default='', max_length=50)),
                ('account_type', models.CharField(default='Savings', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DailyConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_date', models.DateField(default=None, null=True)),
                ('color', models.CharField(default='-', max_length=50)),
                ('unit', models.CharField(max_length=50, null=True)),
                ('quantity', models.FloatField(max_length=15)),
                ('quantity_remaining', models.FloatField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('account_no', models.CharField(max_length=12)),
                ('ifsc', models.CharField(max_length=11)),
                ('account_type', models.CharField(max_length=50)),
                ('aadhar_no', models.CharField(max_length=12)),
                ('contractor_name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GodownLeaseColors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('unit', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Godowns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godown', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingPartyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_party', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualities', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('party_name', models.CharField(default='no', max_length=50)),
                ('bill_no', models.IntegerField()),
                ('bill_date', models.CharField(max_length=30)),
                ('bill_amount', models.FloatField(max_length=15)),
                ('lot_no', models.IntegerField()),
                ('quality', models.CharField(max_length=100)),
                ('than', models.IntegerField()),
                ('mtrs', models.FloatField(max_length=15)),
                ('bale', models.IntegerField()),
                ('rate', models.FloatField(max_length=15)),
                ('lr_no', models.IntegerField()),
                ('order_no', models.IntegerField()),
                ('state', models.CharField(default='Transit', max_length=30)),
                ('bale_recieved', models.IntegerField(default=0)),
                ('recieving_date', models.DateField(default=None, null=True)),
                ('processing_party_name', models.CharField(default='-', max_length=50)),
                ('total_bale', models.IntegerField()),
                ('checker', models.CharField(default='-', max_length=50)),
                ('transport', models.CharField(default='-', max_length=50)),
                ('transport_rate', models.FloatField(default=0, max_length=10)),
                ('checking_date', models.DateField(default=None, null=True)),
                ('processing_type', models.CharField(default='-', max_length=50)),
                ('sent_to_processing_date', models.DateField(default=None, null=True)),
                ('arrival_location', models.CharField(default='-', max_length=50)),
                ('recieve_processed_date', models.DateField(default=None, null=True)),
                ('total_thans', models.IntegerField()),
                ('total_mtrs', models.FloatField()),
                ('tally', models.BooleanField(default=False)),
                ('gate_pass', models.IntegerField(null=True)),
                ('chalan_no', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThanRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range1', models.FloatField(max_length=10)),
                ('range2', models.FloatField(max_length=10)),
                ('rate', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport', models.CharField(max_length=50)),
                ('rate', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=None, null=True)),
                ('amount', models.FloatField()),
                ('last_payment_date', models.DateField(default=None, null=True)),
                ('company_account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventoryapp.CompanyAccounts')),
                ('employee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventoryapp.Employee')),
            ],
        ),
    ]
