# Generated by Django 3.1.2 on 2020-11-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allorders',
            name='unit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='colorrecord',
            name='unit',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
