# Generated by Django 3.1.2 on 2020-10-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='bale_recieved',
            field=models.IntegerField(default=0),
        ),
    ]
