# Generated by Django 3.1.2 on 2020-11-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorrecord',
            old_name='lease_date',
            new_name='bill_date',
        ),
    ]
