# Generated by Django 3.1.2 on 2020-10-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='bill_date',
        ),
        migrations.AlterField(
            model_name='item',
            name='bale',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='bill_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='lot_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='lr_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='order_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='sr_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='than',
            field=models.IntegerField(),
        ),
    ]
