# Generated by Django 3.1.2 on 2020-10-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='bill_date',
            field=models.CharField(max_length=30),
        ),
    ]
