# Generated by Django 3.1.2 on 2020-10-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='total_mtrs',
            field=models.FloatField(),
        ),
    ]
