# Generated by Django 3.1.2 on 2020-10-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='quality2',
        ),
        migrations.AddField(
            model_name='record',
            name='processing_party_name',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='recieving_date',
            field=models.DateField(default='2020-10-28'),
        ),
    ]
