# Generated by Django 3.1.2 on 2020-10-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0002_auto_20201028_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='state',
            field=models.CharField(default='Transit', max_length=30),
        ),
    ]
