# Generated by Django 3.1.2 on 2020-11-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0002_auto_20201102_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='checking_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='recieve_processed_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='recieving_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='sent_to_processing_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
