# Generated by Django 3.1.2 on 2020-10-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0002_record_bale_recieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='recieving_date',
            field=models.DateField(default='2020-10-23'),
        ),
    ]
