# Generated by Django 3.1.2 on 2020-11-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0002_auto_20201122_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorrecord',
            name='bill_no',
            field=models.IntegerField(null=True),
        ),
    ]
