# Generated by Django 3.1.2 on 2020-10-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0002_auto_20201019_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='sr_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
