# Generated by Django 3.1.2 on 2020-11-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0002_checker'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThanRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range1', models.FloatField(max_length=10)),
                ('range2', models.FloatField(max_length=10)),
                ('rate', models.FloatField(max_length=10)),
            ],
        ),
    ]
