# Generated by Django 3.1.2 on 2020-11-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0003_colorrecord_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorrecord',
            name='chalan_no',
            field=models.IntegerField(null=True),
        ),
    ]
