# Generated by Django 3.1.2 on 2020-12-06 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0003_auto_20201206_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='transport_rate',
        ),
        migrations.AlterField(
            model_name='monthlypayment',
            name='company_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.companyaccounts'),
        ),
        migrations.AlterField(
            model_name='monthlypayment',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.employee'),
        ),
        migrations.AlterField(
            model_name='record',
            name='checker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.checker'),
        ),
        migrations.AlterField(
            model_name='record',
            name='processing_party_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.processingpartyname'),
        ),
        migrations.AlterField(
            model_name='record',
            name='transport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.transport'),
        ),
    ]
