# Generated by Django 3.1.2 on 2020-11-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0004_record_checker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allorders',
            name='validation',
            field=models.CharField(default='No', max_length=50, null=True),
        ),
    ]
