# Generated by Django 3.1.2 on 2020-10-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0004_auto_20201019_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='bale',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='bill_amount',
            field=models.FloatField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='bill_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='bill_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='lot_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='lr_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='mtrs',
            field=models.FloatField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='order_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='party_name',
            field=models.CharField(default='no', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='quality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='rate',
            field=models.FloatField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='sr_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='state',
            field=models.CharField(choices=[('state1', 'In transit'), ('state2', 'Order recieved'), ('state3', 'In godown'), ('state4', 'done')], default='transit', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='than',
            field=models.IntegerField(null=True),
        ),
    ]
