# Generated by Django 3.1.2 on 2020-12-06 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0004_auto_20201206_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='quality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.quality'),
        ),
    ]
