# Generated by Django 3.1.2 on 2020-12-07 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0005_auto_20201207_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='processing_party_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.processingpartyname'),
        ),
    ]
