# Generated by Django 3.1.2 on 2020-11-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0005_auto_20201123_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='allorders',
            name='validation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
