# Generated by Django 3.1.2 on 2020-11-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0005_auto_20201126_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorrecord',
            name='a_date',
        ),
        migrations.AddField(
            model_name='colorrecord',
            name='recieving_date_string',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
