# Generated by Django 3.1.2 on 2020-11-30 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0006_auto_20201127_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_account', models.IntegerField()),
                ('account_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('account_no', models.IntegerField()),
                ('ifsc', models.CharField(max_length=50)),
                ('account_type', models.CharField(max_length=50)),
                ('aadhar_no', models.IntegerField()),
                ('contractor_name', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=None, null=True)),
                ('company_account', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('employee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventoryapp.employee')),
            ],
        ),
    ]
