# Generated by Django 3.1.2 on 2020-11-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0006_allorders_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorsupplier',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colorsupplier',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
