# Generated by Django 3.1.2 on 2020-11-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0007_companyaccounts_employee_monthlypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaccounts',
            name='bank_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyaccounts',
            name='ifsc',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
