# Generated by Django 3.1.2 on 2020-11-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0007_auto_20201123_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='allorders',
            name='chalan_no',
            field=models.IntegerField(null=True),
        ),
    ]
