# Generated by Django 3.1.2 on 2020-11-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0008_allorders_chalan_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='chalan_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='gate_pass',
            field=models.IntegerField(null=True),
        ),
    ]
