# Generated by Django 3.1.2 on 2020-12-07 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0008_auto_20201207_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='processing_party_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.processingpartyname'),
        ),
    ]
