# Generated by Django 3.1.2 on 2020-12-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0008_auto_20201130_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayment',
            name='last_payment_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
