# Generated by Django 3.1.2 on 2020-11-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0009_auto_20201123_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='allorders',
            name='rem_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
