# Generated by Django 3.1.2 on 2020-12-01 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0009_monthlypayment_last_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlypayment',
            name='company_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventoryapp.companyaccounts'),
        ),
    ]
