# Generated by Django 3.1.2 on 2020-12-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0010_auto_20201207_1241'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quality',
            new_name='GreyQualityMaster',
        ),
    ]
