# Generated by Django 3.1.2 on 2020-12-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0010_auto_20201201_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaccounts',
            name='account_type',
            field=models.CharField(default='Savings', max_length=50),
        ),
        migrations.AddField(
            model_name='companyaccounts',
            name='branch_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
