# Generated by Django 3.1.2 on 2020-12-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0011_auto_20201207_1308'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArrivalLocation',
            new_name='GreyArrivalLocationMaster',
        ),
        migrations.RenameModel(
            old_name='Checker',
            new_name='GreyCheckerMaster',
        ),
        migrations.RenameModel(
            old_name='ThanRange',
            new_name='GreyCutRange',
        ),
        migrations.RenameModel(
            old_name='Transport',
            new_name='GreyTransportMaster',
        ),
        migrations.RenameModel(
            old_name='ProcessingPartyName',
            new_name='ProcessingPartyNameMaster',
        ),
    ]
