# Generated by Django 3.1.2 on 2020-12-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0011_auto_20201201_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allorders',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='allorders',
            name='rem_quantity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='closingstock',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='colorrecord',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='colorrecord',
            name='total_quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='godownleasecolors',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
