# Generated by Django 3.1.2 on 2020-12-07 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0012_auto_20201207_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allorders',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.color'),
        ),
        migrations.AlterField(
            model_name='allorders',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.colorsupplier'),
        ),
        migrations.AlterField(
            model_name='allorders',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.units'),
        ),
        migrations.AlterField(
            model_name='colorrecord',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.color'),
        ),
        migrations.AlterField(
            model_name='colorrecord',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.colorsupplier'),
        ),
        migrations.AlterField(
            model_name='colorrecord',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.units'),
        ),
    ]
