# Generated by Django 3.1.2 on 2020-12-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0013_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='transport',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='transport_rate',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
