# Generated by Django 3.1.2 on 2020-12-07 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0013_auto_20201207_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorrecord',
            name='godown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.godowns'),
        ),
    ]
