# Generated by Django 3.1.2 on 2020-12-07 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0014_auto_20201207_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='godownleasecolors',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.color'),
        ),
        migrations.AlterField(
            model_name='godownleasecolors',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.godowns'),
        ),
        migrations.AlterField(
            model_name='godownleasecolors',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.units'),
        ),
    ]
