# Generated by Django 3.1.2 on 2020-12-07 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0015_auto_20201207_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='godownleasecolors',
            name='state2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.lease'),
        ),
    ]
