# Generated by Django 3.1.2 on 2020-12-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0016_godownleasecolors_state2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='godownleasecolors',
            old_name='state2',
            new_name='loose_godown_state',
        ),
    ]
