# Generated by Django 3.1.2 on 2020-12-07 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0017_auto_20201207_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closingstock',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.color'),
        ),
        migrations.AlterField(
            model_name='closingstock',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.units'),
        ),
    ]
