# Generated by Django 3.1.2 on 2020-12-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0020_auto_20201208_1206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColorSupplier',
            new_name='ColorAndChemicalsSupplier',
        ),
    ]
