# Generated by Django 3.1.2 on 2020-12-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0021_auto_20201208_1226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Godowns',
            new_name='ChemicalsGodownsMaster',
        ),
    ]
