# Generated by Django 3.1.2 on 2020-12-08 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0022_auto_20201208_1236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lease',
            new_name='ChemicalsLooseGodownMaster',
        ),
    ]
