# Generated by Django 3.1.2 on 2020-12-08 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0023_auto_20201208_1246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Units',
            new_name='ChemicalsUnitsMaster',
        ),
    ]
