# Generated by Django 3.1.2 on 2020-12-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0024_auto_20201208_1252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllOrders',
            new_name='ChemicalsAllOrders',
        ),
    ]
