# Generated by Django 3.1.2 on 2020-12-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0025_auto_20201208_1306'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GodownLeaseColors',
            new_name='ChemicalsGodownLooseMergeStock',
        ),
    ]
