# Generated by Django 3.1.2 on 2020-12-08 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0026_auto_20201208_1306'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClosingStock',
            new_name='ChemicalsClosingStock',
        ),
        migrations.RenameModel(
            old_name='DailyConsumption',
            new_name='ChemicalsDailyConsumption',
        ),
    ]
